config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "flats#index"

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
  validates :price_per_night, :number_of_guests, numericality: { only_integer: true }
  validates :number_of_guests, inclusion: { in: 1..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save

    if @flat.save
      redirect_to flats_path(@flat), notice: "Flat was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)

    if @flat.save
      redirect_to flats_path(@flat), notice: "Flat was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container mt-5">
  <div class="bg-light">
    <%= simple_form_for (@flat) do |f| %>
      <h1>Edit Flat</h1>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guests %>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
    <p class="mt-2"><%= link_to "Back", flats_path%></p>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container">
  <div class="m-2">
    <h1>All our flats</h1>
    <h6>All <%= @flats.length %> flats.</h2>
  </div>
  <div class="d-flex flex-wrap">
    <% @flats.each do |flat| %>
    <div class="card m-2" style="width: 30%;">
      <%= image_tag('pexels-life-of-pix-2459.jpg') %>
      <div class="card-body bg-light">
        <h5 class="card-title"><%= flat.name %></h5>
        <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae placeat, dolorum quasi eos explicabo itaque qui nisi?</p>
        <%= link_to "More info", flat_path(flat), class: "btn btn-primary" %>
        <%= link_to "Edit", edit_flat_path(flat), class: "btn btn-warning" %>
        <%= link_to "Remove", flat_path(flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-5">
  <div class="bg-light">
    <%= simple_form_for (@flat) do |f| %>
      <h1>New Flat</h1>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guests %>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
    <p class="mt-2"><%= link_to "Back", flats_path%></p>
  </div>
</div>

app/views/flats/show.html.erb
<div class="banner"></div>

<div class="container">

  <h1><%= @flat.name %></h1>

  <h3>A bit more about this flat</h3>
  <p><%= @flat.description %></p>

  <h2>Details</h2>
  <p><%= @flat.number_of_guests %> people</p>
  <p><%= @flat.price_per_night %> €</p>
  <p class="mt-2"><%= link_to "Back", flats_path%></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/flats">Simple Airbnb</a>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
          <button class="btn btn-outline-primary ms-2 " type="submit"><%= link_to "Add flat", new_flat_path %></button>
        </form>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>